import React from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import LandingPage from "./Pages/LandingPage";
import ProductPage from "./Pages/ProductPage";
import CartPage from "./Pages/CartPage";
import { CartProvider } from "./context/CartContext";

const products = [
  {
    id: 1,
    name: "Rolex Submariner Date",
    price: 9500,
    originalPrice: 11200,
    image: "https://images.unsplash.com/photo-1518544801976-3e1889b9c2c4?w=700&q=85",
    category: "Watches",
    brand: "Rolex",
    rating: 4.9,
    reviews: 2841,
    badge: "Best Seller",
    description: "The Submariner Date is the reference among divers' watches. Waterproof to a depth of 300 metres, it features the iconic unidirectional rotatable bezel with a Cerachrom insert in black ceramic.",
    features: ["Swiss Automatic Movement", "300m Water Resistance", "Oystersteel Case", "Ceramic Bezel", "Sapphire Crystal"],
    stock: 3,
    deliveryDays: 2,
  },
  {
    id: 2,
    name: "Audemars Piguet Royal Oak",
    price: 24500,
    originalPrice: 28000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=700&q=85",
    category: "Watches",
    brand: "Audemars Piguet",
    rating: 4.8,
    reviews: 1203,
    badge: "Limited",
    description: "The Royal Oak Selfwinding is one of the most iconic luxury sports watches ever created. With its distinctive octagonal bezel and integrated bracelet, it changed fine watchmaking forever.",
    features: ["Calibre 4302 Movement", "50m Water Resistance", "Stainless Steel", "Tapisserie Dial", "Integrated Bracelet"],
    stock: 1,
    deliveryDays: 3,
  },
  {
    id: 3,
    name: "Gucci Ophidia Structured Tote",
    price: 3200,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=700&q=85",
    category: "Bags",
    brand: "Gucci",
    rating: 4.7,
    reviews: 5621,
    badge: "New Arrival",
    description: "The Ophidia Structured Tote in supreme canvas with leather trim. Double G hardware closure, suede interior lining, and removable shoulder strap.",
    features: ["GG Supreme Canvas", "Leather Trim", "Double G Hardware", "Suede Interior", "Dust Bag Included"],
    stock: 8,
    deliveryDays: 2,
  },
  {
    id: 4,
    name: "Hermès Birkin 30",
    price: 18900,
    originalPrice: 20500,
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=700&q=85",
    category: "Bags",
    brand: "Hermès",
    rating: 5.0,
    reviews: 987,
    badge: "Rare Find",
    description: "The Birkin is the world's most coveted handbag. Handcrafted by a single artisan, each Birkin requires 18–25 hours to complete and is made from the finest Togo leather.",
    features: ["Togo Leather", "Palladium Hardware", "Hand-stitched", "Lock & Keys Included", "Certificate of Authenticity"],
    stock: 1,
    deliveryDays: 5,
  },
  {
    id: 5,
    name: "Valentino Noir Evening Gown",
    price: 4800,
    originalPrice: 6200,
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38?w=700&q=85",
    category: "Apparel",
    brand: "Valentino",
    rating: 4.6,
    reviews: 832,
    badge: "SS26",
    description: "A masterpiece of Italian haute couture. Floor-length silk crepe with hand-applied embellishments and a structured boned bodice. Made in Rome.",
    features: ["100% Silk Crepe", "Hand-applied Beading", "Boned Bodice", "Floor Length", "Dry Clean Only"],
    stock: 5,
    deliveryDays: 4,
  },
  {
    id: 6,
    name: "Balenciaga Phantom Sneaker",
    price: 1050,
    originalPrice: 1200,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=700&q=85",
    category: "Shoes",
    brand: "Balenciaga",
    rating: 4.5,
    reviews: 3412,
    badge: "Trending",
    description: "The Phantom Sneaker features an extreme XL outsole, sock-like stretch knit upper, and the iconic Balenciaga branding. A statement in oversized street luxury.",
    features: ["Stretch Knit Upper", "XL Rubber Outsole", "Lace-up Closure", "Padded Collar", "Size: 36–47"],
    stock: 12,
    deliveryDays: 2,
  },
  {
    id: 7,
    name: "Christian Louboutin So Kate 120",
    price: 795,
    originalPrice: 895,
    image: "https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=700&q=85",
    category: "Shoes",
    brand: "Christian Louboutin",
    rating: 4.7,
    reviews: 2108,
    badge: "Iconic",
    description: "The So Kate is perhaps the most famous stiletto in the world. With its 120mm heel and pointed toe, it elongates the leg with unparalleled elegance.",
    features: ["Patent Leather Upper", "120mm Heel", "Pointed Toe", "Leather Sole", "Signature Red Sole"],
    stock: 7,
    deliveryDays: 3,
  },
  {
    id: 8,
    name: "Ray-Ban Aviator Classic",
    price: 185,
    originalPrice: 220,
    image: "https://images.unsplash.com/photo-1511497584788-876760111969?w=700&q=85",
    category: "Accessories",
    brand: "Ray-Ban",
    rating: 4.8,
    reviews: 14203,
    badge: "Best Seller",
    description: "The original aviator, born in 1937 for US military pilots. Crafted with gold-toned metal frame and classic G-15 lenses that offer 100% UV protection.",
    features: ["G-15 Crystal Lenses", "100% UV Protection", "Gold Metal Frame", "Adjustable Nose Pads", "Spring Hinge"],
    stock: 50,
    deliveryDays: 1,
  },
  {
    id: 9,
    name: "Chanel No. 5 EDP 100ml",
    price: 185,
    originalPrice: 210,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=700&q=85",
    category: "Fragrance",
    brand: "Chanel",
    rating: 4.9,
    reviews: 8920,
    badge: "Icon",
    description: "The world's most iconic fragrance since 1921. A floral aldehyde with notes of ylang-ylang, rose absolute, and sandalwood. Timeless femininity in a bottle.",
    features: ["100ml EDP Spray", "Top: Aldehyde, Neroli", "Heart: Rose, Jasmine", "Base: Sandalwood, Vetiver", "Refillable Bottle"],
    stock: 30,
    deliveryDays: 1,
  },
  {
    id: 10,
    name: "Cartier Love Ring 18K Gold",
    price: 1850,
    originalPrice: 2100,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=700&q=85",
    category: "Jewelry",
    brand: "Cartier",
    rating: 4.9,
    reviews: 4301,
    badge: "Timeless",
    description: "The Love ring from Cartier's iconic collection. Crafted in 18K yellow gold with the signature screw motif, it is a symbol of love that endures.",
    features: ["18K Yellow Gold", "Screw Motif Design", "Certificate of Authenticity", "Cartier Box & Pouch", "Complimentary Engraving"],
    stock: 6,
    deliveryDays: 2,
  },
  {
    id: 11,
    name: "Van Cleef Alhambra Necklace",
    price: 6750,
    originalPrice: 7500,
    image: "https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=700&q=85",
    category: "Jewelry",
    brand: "Van Cleef & Arpels",
    rating: 5.0,
    reviews: 1102,
    badge: "Rare Find",
    description: "The Vintage Alhambra necklace in 18K yellow gold with malachite motifs. An emblematic piece of Van Cleef & Arpels, inspired by the four-leaf clover, a symbol of luck.",
    features: ["18K Yellow Gold", "Natural Malachite", "Gold Chain 42cm", "VCA Hallmark", "Original Pouch"],
    stock: 2,
    deliveryDays: 4,
  },
  {
    id: 12,
    name: "Dior Saddle Bag Oblique",
    price: 2950,
    originalPrice: 3400,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=700&q=85",
    category: "Bags",
    brand: "Dior",
    rating: 4.7,
    reviews: 2890,
    badge: "Trending",
    description: "The iconic Dior Saddle Bag reinterpreted in Oblique jacquard canvas. First introduced in 1999, it remains one of the most recognizable silhouettes in fashion.",
    features: ["Oblique Jacquard Canvas", "CD Clasp Closure", "Removable Strap", "Interior Zip Pocket", "Dior Dust Bag"],
    stock: 4,
    deliveryDays: 3,
  },
];

function App() {
  return (
    <CartProvider>
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<LandingPage products={products} />} />
          <Route path="/product/:id" element={<ProductPage products={products} />} />
          <Route path="/cart" element={<CartPage />} />
        </Routes>
      </BrowserRouter>
    </CartProvider>
  );
}

export default App;